config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/facebook/callback' => 'sessions#create' 
  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :users, only: [:new, :create], path_names: {new: 'signup'}

  resources :users, only: [:show] do
    resources :vacations, only: [:show, :edit, :update, :index]
  end
  

  resources :vacations
  resources :destinations
  
  root 'destinations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :vacation_destinations
    has_many :vacations, through: :vacation_destinations
    validates_presence_of :name, :location
end

app/models/user.rb
class User < ApplicationRecord
    has_many :vacations
    has_secure_password
    accepts_nested_attributes_for :vacations
    before_save { self.email = email.downcase }
    validates :email, presence: true, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }

    private

    def self.full_name
        self.first_name + " " + self.last_name
    end
end

app/models/vacation.rb
class Vacation < ApplicationRecord
    belongs_to :user
    has_many :vacation_destinations
    has_many :destinations, through: :vacation_destinations
    accepts_nested_attributes_for :destinations
    
end

app/models/vacation_destination.rb
class VacationDestination < ApplicationRecord
    belongs_to :vacation
    belongs_to :destination
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    include UsersHelper
    include DestinationsHelper
    include VacationsHelper

    private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :get_destination, only: [:show, :edit, :update]
    
    def index
        @destinations = Destination.all
    end

    def new
    end

    def create
        @destination = @vacation.destination.build(destination_params)
        if @destination.save
            flash[:success] = "Destination Created!"
            redirect_to edit_vacation_path(@vacation)
        else
            render :new
        end

    end

    def show
    end

    def edit
    end

    def update
    end

    private

    def get_destination
        @destination = Destination.find_by(params[:id])
    end

    def destination_params
        params.require(:destination).permit(:country, :state, :city, vacation_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
    end

    def show
        @user = User.find_by(id: params[:id])
    end
  
    def destroy
        log_out
        redirect_to root_url
    end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            flash[:success] = "Success! Welcome #{@user.first_name}!"
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    private

    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation,
            vacation_attributes: [:title, :description, :date, :public])
    end

    

end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
    before_action :current_user, only: [:create, :show]
    def new
        @vacation = Vacation.new
    end

    def create
        
        @vacation = @current_user.vacations.build(vacation_params)
        if @vacation.save
            flash[:success] = "Vacation Created!"
            redirect_to user_path(@current_user, @vacation)
        else
            render :new
        end

    end

    def show
    end

    def edit
    end

    def update
    end

    private

    def vacation_params
        params.require(:vacation).permit(:title, :description, :date, :public, destination_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
    def exists?(destination)
        Destination.find_by(city: destination.city)
    end

    def city_state_country(destination)
        destination.city + ", " + destination.state + " " + destination.country
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user 
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end

    def logged_in?
      !current_user.nil?
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    def current_user?(user)
      user == current_user
    end

    def redirect_back_or(default)
      redirect_to(session[:forwarding_url] || default)
      session.delete(:forwarding_url)
    end

    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end

end

app/helpers/users_helper.rb
module UsersHelper
    # def full_name(user)
    #     user.first_name + " " + user.last_name
    # end
end

app/helpers/vacations_helper.rb
module VacationsHelper
    def current_vacation
        @vacation ||= Vacation.find_by(params[:id])
    end
end

app/views/destinations/index.html.erb
<h1> Our members have been all over! </h1><br>
<h3> Members have visited: </h3>
    <ul>
        <% @destinations.each do |d| %>
            <li><%= link_to city_state_country(d), destination_path(d) %></li>
        <% end %>
    </ul>
<br>

app/views/destinations/new.html.erb
<h1>Add A New Destination</h1>
<%= form_with model: @destination, url: edit_vacation_path(@vacation) do |f| %>
    <br>
    <%= f.label :city %>
    <%= f.text_field :city %>
    <br>
    <%= f.label :state %>
    <%= f.text_field :state %>
    <br>
    <%= f.label :country %>
    <%= f.text_field :country %>
    <br>
<p><%= f.submit %></p>
    <% end %> 

app/views/destinations/show.html.erb
<h1> <%= @destination.name %> </h1>

app/views/layouts/_header.html.erb
<nav class="navbar mb-2">
    <div class="container-fluid">
        <div class="navbar-header">
            <%= link_to "Home", root_path, class: "mx-2" %>
        </div>
        <% if logged_in? %>
            <ul class="nav navbar-right ">
                <li><%= link_to "My Vacations", user_path(@current_user), class: "mx-2" %></li>
                <li><%= link_to "Log out", logout_path, class: "mx-2", method: :delete %></li> 
            </ul>
        <% else %>
            <ul class="nav navbar-right ">
                <li><%= link_to "Log in", login_path, class: "mx-2" %></li> 
                <li><%= link_to "Sign up", signup_path, class: "mx-2" %></li>
            </ul>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>RailsTravelTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class='text-danger'><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class='text-center'> Sign Up</h1>
<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'mb-1 form-control' %>
        <br>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'mb-1 form-control' %>
        <br>
        <%= f.label :username %>
        <%= f.text_field :username, class: 'mb-1 form-control' %>
        <br>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'mb-1 form-control' %>
        <br>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'mb-1 form-control' %>
        <br>
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'mb-1 form-control' %>

        <%= f.submit "Sign Up", class: "mt-2 btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Hey there, <%= @current_user.first_name %>!</h1><br>
<h3>Your Vacations:</h3>
<% @current_user.vacations.each do |v| %>
    <ul>
    <li><%= v.date %></li>
    <li><%= link_to v.title, user_vacation_path(v) %></li>
    <br>
    </ul>
<% end %>
<%= link_to "Add Another Adventure", new_vacation_path %>

app/views/vacations/new.html.erb
<h1>Add Your New Vacation</h1>
<%= form_with model: @vacation do |f| %>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <br>
    <br>
    <h3> Add Some Stops on Your Trip </h3>
    <p> Need Recommendations? </p
    <%= f.collection_check_boxes(:destination_ids, Destination.all, :id, :city) %>
<p><%= f.submit %></p>
    <% end %>
     
        

app/views/vacations/show.html.erb
<h1>Hello?</h1>